/**
 * Wasm Decompiler Bridge — Deep Recon (desktop, inlined)
 * No Electron deps. wasm2wat (wabt), scan, JS stubs.
 */

import { spawn } from 'child_process';
import { access } from 'fs/promises';
import path from 'path';

const WASM2WAT_TIMEOUT_MS = 30_000;
const WAT_SCAN_MAX_CHARS = 2_000_000;

export type WasmReconResult = {
  ok: boolean;
  path: string;
  url?: string;
  error?: string;
  wat?: string;
  watLength?: number;
  endpoints: string[];
  keys: string[];
  crypto: string[];
  exportedFuncs: string[];
  jsStubs: string;
};

const ENDPOINT_REGEX = /https?:\/\/[a-zA-Z0-9][-a-zA-Z0-9.]*(?::[0-9]+)?(?:\/[^\s"']*)?|wss?:\/\/[^\s"']+|(?:"|')\/(?:api|v[0-9]+|graphql|ws|auth|oauth)[^\s"']*(?:"|')|(?:\/[\w.-]+){2,}/g;
const KEY_REGEX = /(?:Bearer\s+)[A-Za-z0-9_.-]{20,}|(?:sk_|pk_)[a-zA-Z0-9]{20,}|[A-Za-z0-9+/]{32,}={0,2}|[a-fA-F0-9]{32,}|"(?:api[_-]?key|secret|token|auth|password)"\s*:\s*"[^"]{16,}"/g;
const CRYPTO_REGEX = /(?:i32|i64|f32|f64)\.(?:xor|rotl|rotr|and|or|shl|shr)|(?:import\s+[^"']*"(?:crypto|Crypto|getRandomValues|subtle|encrypt|decrypt|sign|verify|digest|hash|hmac|aes|sha|md5)[^"']*")|(?:^\s*[;(].*?(?:encrypt|decrypt|sign|hash|key|nonce|iv)\b)/gim;
const EXPORT_FUNC_REGEX = /\(export\s+"([^"]+)"\s*\(\s*func\s+/g;

function uniq(arr: string[]): string[] { return [...new Set(arr)]; }
function truncate(s: string, max: number): string { return s.length <= max ? s : s.slice(0, max) + '...[truncated]'; }

export async function resolveWasmPath(wasmPath: string, projectRoot?: string): Promise<string | null> {
  const candidates = [wasmPath, path.isAbsolute(wasmPath) ? wasmPath : path.join(process.cwd(), wasmPath)];
  if (projectRoot) {
    candidates.push(path.join(projectRoot, wasmPath));
    candidates.push(path.join(projectRoot, 'wasm-captures', path.basename(wasmPath)));
  }
  for (const p of candidates) {
    try { await access(p); return p; } catch { /* skip */ }
  }
  return null;
}

export async function decompileToWat(wasmPath: string): Promise<{ wat: string } | { error: string }> {
  return new Promise((resolve) => {
    let stderr = '', stdout = '';
    const proc = spawn('wasm2wat', [wasmPath], { stdio: ['ignore', 'pipe', 'pipe'] });
    const to = setTimeout(() => { try { proc.kill('SIGKILL'); } catch { /* ignore */ } resolve({ error: `wasm2wat timed out after ${WASM2WAT_TIMEOUT_MS}ms` }); }, WASM2WAT_TIMEOUT_MS);
    proc.stdout?.on('data', (d: Buffer) => { stdout += d.toString('utf-8'); });
    proc.stderr?.on('data', (d: Buffer) => { stderr += d.toString('utf-8'); });
    proc.on('error', (e) => { clearTimeout(to); resolve({ error: `wasm2wat not found: ${e.message}. Install wabt: brew install wabt` }); });
    proc.on('close', (code, sig) => {
      clearTimeout(to);
      if (code !== 0 && sig !== 'SIGKILL') { resolve({ error: `wasm2wat exited ${code}: ${truncate(stderr || stdout, 500)}` }); return; }
      if (!stdout || !stdout.trim()) { resolve({ error: 'wasm2wat produced no output' }); return; }
      resolve({ wat: stdout });
    });
  });
}

export function scanForSecrets(wat: string): { endpoints: string[]; keys: string[]; crypto: string[] } {
  const s = wat.length > WAT_SCAN_MAX_CHARS ? wat.slice(0, WAT_SCAN_MAX_CHARS) : wat;
  return {
    endpoints: uniq((s.match(ENDPOINT_REGEX) || []).map((x) => x.replace(/^["']|["']$/g, '').trim()).filter(Boolean)),
    keys: uniq((s.match(KEY_REGEX) || []).map((x) => truncate(x, 120)).filter(Boolean)),
    crypto: uniq((s.match(CRYPTO_REGEX) || []).map((x) => x.trim()).filter(Boolean).slice(0, 100)),
  };
}

export function extractExportedFuncs(wat: string): string[] { return uniq(Array.from(wat.matchAll(EXPORT_FUNC_REGEX), (x) => x[1])); }

export function toJavaScriptStubs(exportedFuncs: string[], endpoints: string[], keys: string[]): string {
  const lines = ['// Generated by wasm-recon. Replace bodies with actual logic.', '// Endpoints: ' + endpoints.slice(0, 10).join(', '), '// Keys: ' + keys.slice(0, 5).map((k) => truncate(k, 40)).join(', '), ''];
  for (const name of exportedFuncs) {
    const safe = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : `['${name.replace(/'/g, "\\'")}']`;
    lines.push(`export function ${safe}(...args) { throw new Error('Stub: ${name}'); }`, '');
  }
  if (exportedFuncs.length === 0) lines.push('// No exported functions found.');
  return lines.join('\n');
}

export async function runWasmRecon(wasmPath: string, opts?: { url?: string; projectRoot?: string }): Promise<WasmReconResult> {
  const resolved = await resolveWasmPath(wasmPath, opts?.projectRoot);
  if (!resolved) return { ok: false, path: wasmPath, url: opts?.url, error: `wasm file not found: ${wasmPath}`, endpoints: [], keys: [], crypto: [], exportedFuncs: [], jsStubs: '' };
  const decomp = await decompileToWat(resolved);
  if ('error' in decomp) return { ok: false, path: resolved, url: opts?.url, error: decomp.error, endpoints: [], keys: [], crypto: [], exportedFuncs: [], jsStubs: '' };
  const wat = decomp.wat;
  const { endpoints, keys, crypto } = scanForSecrets(wat);
  const exportedFuncs = extractExportedFuncs(wat);
  return {
    ok: true, path: resolved, url: opts?.url,
    wat: wat.length > WAT_SCAN_MAX_CHARS ? wat.slice(0, WAT_SCAN_MAX_CHARS) + '\n...[truncated]' : wat,
    watLength: wat.length, endpoints, keys, crypto, exportedFuncs, jsStubs: toJavaScriptStubs(exportedFuncs, endpoints, keys),
  };
}

export async function runWasmReconFromBuffer(buf: Buffer, destPath: string, opts?: { url?: string }): Promise<WasmReconResult> {
  const { writeFile } = await import('fs/promises');
  try { await writeFile(destPath, buf); return runWasmRecon(destPath, { ...opts, projectRoot: path.dirname(destPath) }); }
  catch (e) { return { ok: false, path: destPath, url: opts?.url, error: `Failed to write wasm: ${(e as Error).message}`, endpoints: [], keys: [], crypto: [], exportedFuncs: [], jsStubs: '' }; }
}
